import type { ApprovalPattern } from './types'

export const approvalPatterns: ApprovalPattern[] = [
  {
    id: 'threshold-gate', index: '01', name: 'Threshold gate',
    summary: 'Pause only when a defined boundary is crossed.',
    purpose: 'Protect material limits without forcing humans to review routine work.',
    suitableWhen: ['A measurable boundary exists', 'False negatives are visible', 'Threshold ownership is clear'],
    failureMode: 'The score becomes a substitute for judgement, or the threshold quietly drifts out of date.',
    recordRequirements: ['Threshold and version', 'Observed value', 'Boundary owner', 'Override rationale'],
    demo: { situation: 'A credit exceeds the service-recovery allowance.', proposedAction: 'Issue £640 credit.', evidence: ['Policy cap £500', 'Customer impact: high'] },
  },
  {
    id: 'evidence-review', index: '02', name: 'Review with evidence',
    summary: 'Place decision-relevant evidence beside the proposal.',
    purpose: 'Make review about the decision rather than trusting the fluency of the recommendation.',
    suitableWhen: ['Evidence can be bounded', 'Sources remain inspectable', 'Interpretation matters'],
    failureMode: 'Evidence volume creates the appearance of diligence while hiding the material fact.',
    recordRequirements: ['Evidence snapshot', 'Source provenance', 'Known gaps', 'Reviewer interpretation'],
    demo: { situation: 'A supplier payment is held after a policy mismatch.', proposedAction: 'Release payment.', evidence: ['PO matched', 'Bank detail changed 2 days ago'] },
  },
  {
    id: 'edit-and-approve', index: '03', name: 'Edit and approve',
    summary: 'Let the human alter the proposal before authorising it.',
    purpose: 'Preserve human judgement when the AI is directionally useful but operationally imperfect.',
    suitableWhen: ['Edits are safe to express', 'Changes can be validated', 'Original proposal remains visible'],
    failureMode: 'Human edits bypass the safeguards applied to the original AI proposal.',
    recordRequirements: ['Original proposal', 'Human changes', 'Post-edit validation', 'Final authorised action'],
    demo: { situation: 'An AI drafts customer compensation.', proposedAction: 'Refund 100% and waive next invoice.', evidence: ['12-hour outage', 'Contract allows 30% credit'] },
  },
  {
    id: 'escalation-gate', index: '04', name: 'Escalation gate',
    summary: 'Route uncertainty or consequence to someone with the right authority.',
    purpose: 'Prevent a reviewer from being asked to own a decision they are not equipped to make.',
    suitableWhen: ['Authority levels are explicit', 'Escalation has an SLA', 'Context travels with the case'],
    failureMode: 'Escalation becomes a dead-end queue or a way to diffuse responsibility.',
    recordRequirements: ['Escalation trigger', 'Authority route', 'Time waiting', 'Final owner'],
    demo: { situation: 'A campaign references a sensitive public event.', proposedAction: 'Publish revised campaign.', evidence: ['Brand risk elevated', 'Legal review not completed'] },
  },
  {
    id: 'two-person-rule', index: '05', name: 'Two-person rule',
    summary: 'Require independent confirmation for severe or irreversible actions.',
    purpose: 'Reduce single-person error and coercion where consequences justify added friction.',
    suitableWhen: ['The action is rare and severe', 'Reviewers are independent', 'Disagreement has a route'],
    failureMode: 'The second reviewer simply follows the first, adding latency without independence.',
    recordRequirements: ['Separate decisions', 'Order and timing', 'Conflicts', 'Resolution authority'],
    demo: { situation: 'An AI proposes disabling 4,200 customer accounts.', proposedAction: 'Suspend accounts.', evidence: ['Fraud signal 0.89', 'False-positive baseline 6%'] },
  },
  {
    id: 'sampled-oversight', index: '06', name: 'Sampled oversight',
    summary: 'Review a representative slice instead of every routine action.',
    purpose: 'Detect drift and emerging failure without turning oversight into queue-clearing.',
    suitableWhen: ['Actions are numerous and reversible', 'Sampling is risk-aware', 'Failures feed back into controls'],
    failureMode: 'Easy cases dominate the sample while rare harmful cases remain invisible.',
    recordRequirements: ['Sampling method', 'Population size', 'Findings', 'Control changes'],
    demo: { situation: 'An AI categorises 18,000 support messages.', proposedAction: 'Route messages automatically.', evidence: ['Weekly sample 240', 'Disagreement rate 3.4%'] },
  },
  {
    id: 'time-bound-delegation', index: '07', name: 'Time-bound delegation',
    summary: 'Grant bounded authority that expires automatically.',
    purpose: 'Allow operational speed during known conditions without creating permanent autonomy by accident.',
    suitableWhen: ['Scope and duration are explicit', 'Actions remain monitored', 'Authority can be revoked'],
    failureMode: 'Temporary permission becomes normal operating practice without review.',
    recordRequirements: ['Delegator', 'Scope', 'Start and expiry', 'Actions taken', 'Revocation'],
    demo: { situation: 'A service incident creates a two-hour response window.', proposedAction: 'Auto-issue credits under £80.', evidence: ['Incident declared', '2,100 affected accounts'] },
  },
  {
    id: 'reversible-execution', index: '08', name: 'Reversible execution',
    summary: 'Act first only when the action can be safely undone and observed.',
    purpose: 'Move oversight from pre-approval to monitored correction for low-consequence work.',
    suitableWhen: ['Rollback is real and tested', 'Impact is bounded', 'Detection is fast'],
    failureMode: 'A nominal undo path is mistaken for recovery even though downstream effects persist.',
    recordRequirements: ['Action and scope', 'Rollback window', 'Observed outcome', 'Undo attempt and residual effect'],
    demo: { situation: 'An AI reorders internal knowledge results.', proposedAction: 'Publish ranking update.', evidence: ['Canary group 5%', 'One-click rollback tested'] },
  },
]
